# Generated by Django 5.0.2 on 2024-02-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='tool_img',
            new_name='book_img',
        ),
    ]
